### ISSUE TITLE
Update example/http-server.js for newer (0.4.x) Journey APIs

### ISSUE THREAD

**Issue by indexzero** [cloudhead/journey#13]
Single commit: a3501b5cc3dadbdeb1423c67d7cd3d89303422ac ... cherry-pick when you get a chance.

**Comment by crocodile** [comment]
Ahh..Thanks indexzero! I have been trying to figure out what's wrong with it. (as I am new to Javascript and Node.js)

**Comment by indexzero** [comment]
This library is no longer actively maintained. I recommend using `director`: https://github.com/flatiron/director
