### ISSUE TITLE
More liberal content-type header 

### ISSUE THREAD

**Issue by berb** [cloudhead/journey#2]
Hi again,

http://github.com/cloudhead/journey/blob/master/lib/journey.js#L307

Should be changed in order to accept requests with additional charset information.
For instance, "Content-Type: application/json; charset=UTF-8" would not be accepted so far.

Greets

**Comment by cloudhead** [comment]
Thanks, fixed in 0.2.2!

http://github.com/cloudhead/journey/commit/f4f46c62a482f62427a9ac9695341cb16a306e82

**Comment by berb** [comment]
Thank you.
