### ISSUE TITLE
Trailing slashs is anoying me

### ISSUE THREAD

**Issue by Bwen** [cloudhead/journey#22]
Hi,

If I put: .post("/somename") then it does not catch the url "/somename/". If I put: .post("/somename/") then it does not catch the url "/somename"...

I tried making a regexp for an OR on the trailing slash... but you seem to butcher the Regexp internally...

Would be nice to be able to have 1 event and support both the trailing slash and without.

Thanks,
Bwen

**Comment by coen-hyde** [comment]
I've been using /\/route[/]?/ and it's been working fine

**Comment by Bwen** [comment]
oh.. I was trrying /\/route[|/]/
I guess my Regex is rusty.

Thx.
