### ISSUE TITLE
for some reason I'm getting TypeError: Cannot read property 'unshift' of undefined

### ISSUE THREAD

**Issue by quidcomobile** [cloudhead/journey#29]
in a clean project, I just required journey and I'm getting this error

```
/Users/alex/code/js/qPlatformMock/node_modules/journey/lib/journey.js:3
require.paths.unshift(path.join(__dirname, 'vendor')
```

node -v = 5.3.0, it sounds quite awkward, any idea what I'm doing wrong?

**Comment by indexzero** [comment]
This code is ancient. It is not designed to work with the latest versions of node. Use something like `director` or `express.Router` instead
