### ISSUE TITLE
Add auth() API

### ISSUE THREAD

**Issue by indexzero** [cloudhead/journey#6]
Add an API on top of the filter() API to allow for a simplier implementation of HTTP Basic Auth.

**Comment by berb** [comment]
Passing the username of the authorized user to the bind function would provide an additional bonus. Don't know if this is possible with the current filter API.

**Comment by indexzero** [comment]
That is outside the scope of that issue and probably won't land because we want the `bind` function handlers to be consistent with other middleware layers. The way I would suggest doing this is

<pre>
  function myAuth (req, body, callback) {
    if (/* Your Auth stuff passes */) {
      req.username = 'whateverYourUserNameIs';
      callback();
    }
  }
</pre>

**Comment by indexzero** [comment]
This library is no longer actively maintained. I recommend using `director`: https://github.com/flatiron/director
