### ISSUE TITLE
body as member of request

### ISSUE THREAD

**Issue by xla** [cloudhead/journey#8]
Hej,

I don't fully understand why the body gets merged into the params instead of being an object under the request object. With the merge it's hard to handle the body on it's own. Also the original documentation is showing that the body was once part of the request object. I'd like to understand the motivation and if it's possible to change it back so body is part of the request object. In the case it's needed I could provide a pull request with tests.

-alx

**Comment by tunnckoCore** [comment]
Yea, good point. In most places it have "body" key, but value aways is null.
Plus buggie post response.. How can i get it and handle it? :D
