### ISSUE TITLE
journey error... 

### ISSUE THREAD

**Issue by pradeepthundiyil** [cloudhead/journey#9]
/usr/local/lib/node/.npm/journey/0.4.0-pre-2/package/lib/journey.js:82
        if (arguments[0].headers) { throw new(Error)("Router#route method rena
                                          ^
Error: Router#route method renamed to 'handle'
    at Object.route (/usr/local/lib/node/.npm/journey/0.4.0-pre-2/package/lib/journey.js:82:43)

**Comment by cloudhead** [comment]
You just have to rename your `route` call to `handle`, as the error states, the api changed.
